# Generated by Django 5.0.3 on 2024-03-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=10)),
                ('author_name', models.CharField(max_length=20)),
                ('publication', models.CharField(max_length=20)),
                ('book_price', models.IntegerField()),
                ('book_quantity', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('Online', 'ONLINE'), ('Cash', 'Cash On Delivery')], max_length=10)),
            ],
        ),
    ]
